"""Typing stubs for the `bytetok._bpe_rs` Rust extension module.

This file provides static type information for the compiled PyO3
module `bytetok._bpe_rs` so that type checkers such as Pyright can resolve
exported symbols like `RustBPETrainer`.
"""

from __future__ import annotations

class RustBPETrainer:
    def __init__(self, tokens: list[int], next_token_id: int) -> None: ...
    def train(self, num_merges: int) -> None: ...
    def merge_step(self) -> bool: ...
    def get_tokens(self) -> list[int]: ...
    def get_merge_history(self) -> list[tuple[tuple[int, int], int]]: ...
    def print_state(self) -> None: ...
